CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(50) PRIMARY KEY,
  status VARCHAR(20) NOT NULL DEFAULT 'DISCONNECTED'
    CHECK (status IN ('CONNECTED', 'DISCONNECTED', 'CONNECTING', 'QR_CODE')),
  phone VARCHAR(20),
  qr_code TEXT,
  last_connected_at TIMESTAMPTZ,
  last_disconnected_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_sessions_updated_at') THEN
    CREATE TRIGGER update_sessions_updated_at
      BEFORE UPDATE ON sessions
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS baileys_creds (
  session_id VARCHAR(50) PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,
  creds JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_baileys_creds_updated_at') THEN
    CREATE TRIGGER update_baileys_creds_updated_at
      BEFORE UPDATE ON baileys_creds
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS baileys_keys (
  session_id VARCHAR(50) REFERENCES sessions(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  key_id VARCHAR(255) NOT NULL,
  value JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (session_id, type, key_id)
);

CREATE INDEX IF NOT EXISTS idx_baileys_keys_lookup ON baileys_keys(session_id, type);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_baileys_keys_updated_at') THEN
    CREATE TRIGGER update_baileys_keys_updated_at
      BEFORE UPDATE ON baileys_keys
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(50) NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  trigger_type VARCHAR(20) NOT NULL DEFAULT 'EQUALS'
    CHECK (trigger_type IN ('EQUALS', 'CONTAINS', 'STARTS_WITH', 'REGEX')),
  trigger_value TEXT NOT NULL,
  response_value TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rules_session_active ON rules(session_id, is_active);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_rules_updated_at') THEN
    CREATE TRIGGER update_rules_updated_at
      BEFORE UPDATE ON rules
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS message_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(50) NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  message_id VARCHAR(100) NOT NULL,
  remote_jid VARCHAR(100) NOT NULL,
  push_name VARCHAR(100),
  content TEXT,
  from_me BOOLEAN NOT NULL DEFAULT FALSE,
  occurred_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_message_logs_session_message UNIQUE (session_id, message_id)
);

CREATE INDEX IF NOT EXISTS idx_message_logs_lookup
  ON message_logs(session_id, remote_jid, occurred_at DESC);
